# Generated by Django 5.1.4 on 2025-01-10 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='RoleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roles.product')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Roles.role')),
            ],
            options={
                'db_table': 'role_products',
                'unique_together': {('role', 'product')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='products',
            field=models.ManyToManyField(related_name='roles', through='Roles.RoleProduct', to='Roles.product'),
        ),
    ]
